Basics of Numpy and Operations

In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [8]:
arr1 = np.array([[2, 4, 5, 3, 7, 9]]) ##2D Array
arr1.reshape(1,6)
print(arr1)
arr1.shape

[[2 4 5 3 7 9]]


(1, 6)

In [12]:
arr = np.array([[1, 2, 3, 5], [3, 2, 4, 5], [3, 2, 4, 3]])
print(arr)

[[1 2 3 5]
 [3 2 4 5]
 [3 2 4 3]]


In [14]:
##Attributes of NumPy Array
arr = np.array([[1,2,1,2], [2,4,3,5]])

print("Array: \n", arr)
print("Shape of Array: ", arr.shape)
print("Number of Dimension: ", arr.ndim)
print("Data type of an Array: ", arr.dtype)

Array: 
 [[1 2 1 2]
 [2 4 3 5]]
Shape of Array:  (2, 4)
Number of Dimension:  2
Data type of an Array:  int32
